import Head from "next/head";
import Download from "../components/Download";

import Framework from "../components/Framework";
import Header from "../components/Header";
import Hero from "../components/Hero";
import Improvements from "../components/Improvements";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="w-full min-h-screen font-Poppins bg-gray-900 text-white">
        <div className="max-w-7xl mx-auto py-10 px-8">
          <Header />
          <Hero />
          <Framework />
          <Improvements />
          <Download />
        </div>
      </div>
    </div>
  );
}
